version: "3.9"

services:
  web:
    build: .
    container_name: fastapi_app_1
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:qwerty@db/test_db
    volumes:
      - .:/app

  db:
    image: postgres:13
    container_name: postgres_db_1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
